---
title: "Intro to Bonds"
date: 06/07/2026
date-modified: last-modified
date-format: long
---

### Bond
A bond is a debt issued by issuer/debtor/borrower which is repaid to investor/lender the original amount borrowed + interest over specified period of time.\
A typical bond has a *`fixed date when the amount borrowed is due (principal issued is paid back) aka maturity date`*  and *`contractual amount of interest which is paid every six months`*

### Sectors of U.S. Bond Market
U.S. Fixed income market is divided into six sectors:

* _U.S. Treasury_ : Includes securities issued by U.S. Government. These include Treasury Bills, Notes and Bonds. U.S. Govt securities set the tone for rest of the economy and world
* _Agency_ : Securities issued by federally related institutes and government sponsored entities (GSE). The securities that are not backed by collateral and also called as *_agency debenture securities_*
* _Municipals_ : These bonds are issued by state and local governments. There are two types of bonds based on how the interest received by investors is taxed at federal income tax level. There are two types of bond structures:
    + Tax Backed Bonds
    + Revenue Bonds
* _Corporates_ : These include securities issued by U.S. Corporations and securities issued in U.S. by non U.S. Corporations. Corporations can issue *bonds, medium term notes and commercial paper*. Corporations can also borrow from commercial banks and sometimes these commercial loans can be traded in the market. Based on credit rating of corporations the securities are further classified into investment-grade and non investment-grade
* _Asset Backed Securities_ : Corporations can also raise debt; To issue securities, Corporations use pool of loans or receivables. Usually finance subsidiary of operating companies are issuers of Asset Backed Securities. Other kind of ABS include bonds issued by performing artists backed by their future receivables on music royalties - *Bowie Bonds*
* _Mortgages_ : Mortgages are also part of bond market. The issuances in this sector are backed by loans issued to borrowers to buy single-four family homes or commercial properties (income producing properties such as apartment buildings, office buildings, industrial properties, hotels and healthcare centers). Loans are classifed based on if they conform to the underwriting standards of Federal Agencies or Government Sponsored Entities. The GSEs package residential loans and create *Residential Mortgage Backed Securities (RMBS)*. The RMBS issued by federal agency are reffered as *Agency Mortgage Backed Securities* and RMBS not issued by federal agencies are called *Non agency Mortgage Backed Securities*. *Non agency Mortgage Backed Securities* are divided into prime and non prime mortgage backed securities, the latter are mortgages of borrowers with impaired credit. The classification is shown in figure @fig-MBS
```{mermaid}
%%| label: fig-MBS
%%| fig-cap: "Mortgage Backed Securities Classification"
flowchart LR
  A[Loan] --> C{Is Loan Conforming Underwriting Standards of Federal Agency}
  C -->|Yes| D[Agency MBS] 
  C -->|No|E[Non Agency MBS] --> F{Is Credit Quality of Borrower Good?}
  F -->|No| G[Subprime Mortgage Backed Securities]
  F -->|Yes| H[Prime Mortgage Backed Securities]
```
### Bond Features

* _Type of Issuer_ : There are three issuers of bonds. Governmanet and it's agencies, Muncipal Governments and Corporations (Domestic and Foreign)
* _Term to Maturity_ : Also known as *`Maturity`* or *`Term`*. It is the number of years/months over which issuer has promised to meet the conditions of obligation. At the time of maturity date, the debt will cease it exist and issuer/borrower will pay the outstanding principal and redeem the bond. There are some provisions in indenture (bond prospectus) where issuer may alter the term to maturity. Based on term to maturity, bonds are classified into following categories:
    - Short Term : 1 to 5 years
    - Intermediate Term: 5 to 12 years
    - Long Term : > 12 years
Note that, the higher the term to maturity, the greater the price volatility bond exhbits
* _Principal and Coupon Rate_ : 
    - *Principal Value* :  The amount that borrower promised to pay to bond holder at the time of maturity. It also known as *`maturity value, par value, face value, redemption value`*
    - *Coupon Rate* :  *`Coupon Rate or Nominal Rate`* is rate borrower/issuer promises to pay every year till the maturity date. The dollar amount the investor of bond can expect to receive each year is called *`Coupon`* . For example, if a bond with face value of $\$1000$ agrees to pay $9 \%$  coupon rate for term of maturity of 5 years, then the owner of bond can expect to get paid $\$90$ every year for 5 years. In U.S. and Japan bonds pay coupons semi anually.
        - Not all bonds pay coupons periodically, the type of bonds that donot pay coupon is called **_Zero Coupon Bond_**. The borrower/issuer issues the bond at discount and makes the principal and interest payment at maturity.